### ISSUE TITLE
gofmt

### ISSUE THREAD

**Issue by bcho** [appleboy/gofight#25]
Why use 2 spaces? You can config your editor to treat tab as 2 spaces.

**Comment by appleboy** [comment]
Please see [.editorconfig](https://github.com/appleboy/gofight/blob/master/.editorconfig). I use tab indent and tab size is `2`. You can change the default setting in `.editorconfig` file.

**Comment by bcho** [comment]
wow, I don't know GitHub has supported editorconfig already, my bad :)
