### ISSUE TITLE
Echo v3 is now released and breaks dependencies

### ISSUE THREAD

**Issue by mdouchement** [appleboy/gofight#38]
The new [release](https://github.com/labstack/echo/tree/v3.0.0) of Echo is now on master branch so the gofight's dependencies are broken.

`fasthttp` has been dropped and only `net/http` is used.

**Comment by appleboy** [comment]
Nice. I will take it.

**Comment by appleboy** [comment]
@shawnzhu @mdouchement Please update to `v2.0.0`

**Comment by mdouchement** [comment]
It works now.
Thanks for your quick update.
