### ISSUE TITLE
go fight.HTTPResponse masking ResponseRecorder methods?

### ISSUE THREAD

**Issue by apsdsm** [appleboy/gofight#72]
I might be missing something totally obvious here. If so I apologize in advance. 

It seems like by aliasing `*httptest.ResponseRecorder` with `HTTPResponse`, you can no longer access the methods on the ResponseRecorder object. This means to access headers you must use the deprecated HeaderMap object, rather than calling the Header() method as is suggested.

Is there a way to call the method on the type aliased object? 

It doesn't look like there's a huge amount of gain from aliasing the object outside saving a few keystrokes, so would it be possible to just use the actual object instead of the aliased one? I'd be happy to put a pull request together, though this would change the public interface of the project..

Any guidance in this matter would be appreciated!!

Thank you for making this library btw, it's made my life much nicer!

**Comment by tolgaatam** [comment]
I am running into the same problem right now. How were you able to fix or work around this? I do not wish to use the deprecated `HeaderMap()` method neither.

**Comment by tolgaatam** [comment]
I found one solution to this problem. As `gofight.HTTPResponse` type is an alias for `httptest.Response` , it is possible to do a conversion. Then you can use the methods of `httptest.Response` freely. Here is an example code:

```
g := gofight.New()
g.POST("/api/signup").
	SetJSON(gofight.D{
		"email":          "test@test.com",
		"password":      "1234",
	}).
	Run(engine, func(response gofight.HTTPResponse, request gofight.HTTPRequest) {
		assert.Equal(t, http.StatusOK, response.Code)
		r := (*httptest.ResponseRecorder) (response)
		cookies := r.Header.Get("Cookie")
		
		for _, cookie := range strings.Split (cookies, ";") {
			cookie := strings.TrimSpace()
			......
			......
		}
	})
```

**Comment by appleboy** [comment]
Fixed in https://github.com/appleboy/gofight/releases/tag/v2.2.0

basic example

```go
package example

import (
	"io"
	"net/http"
)

func basicHelloHandler(w http.ResponseWriter, r *http.Request) {
	// add header in response.
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("X-Version", "0.0.1")
	_, _ = io.WriteString(w, "Hello World")
}

// BasicEngine is basic router.
func BasicEngine() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/", basicHelloHandler)

	return mux
}
```

testing

```go
package example

import (
	"net/http"
	"testing"

	"github.com/appleboy/gofight/v2"
	"github.com/stretchr/testify/assert"
)

func TestBasicHelloWorld(t *testing.T) {
	r := gofight.New()
	version := "0.0.1"

	r.GET("/").
		// trun on the debug mode.
		SetDebug(true).
		SetHeader(gofight.H{
			"X-Version": version,
		}).
		Run(BasicEngine(), func(r gofight.HTTPResponse, rq gofight.HTTPRequest) {
			assert.Equal(t, version, rq.Header.Get("X-Version"))
			assert.Equal(t, version, r.Header().Get("X-Version"))
			assert.Equal(t, "Hello World", r.Body.String())
			assert.Equal(t, http.StatusOK, r.Code)
		})
}

func basicHTTPHelloHandler() {
	http.HandleFunc("/hello", basicHelloHandler)
}

func TestBasicHttpHelloWorld(t *testing.T) {
	basicHTTPHelloHandler()

	r := gofight.New()

	r.GET("/hello").
		// trun on the debug mode.
		SetDebug(true).
		Run(http.DefaultServeMux, func(r gofight.HTTPResponse, rq gofight.HTTPRequest) {
			assert.Equal(t, "Hello World", r.Body.String())
			assert.Equal(t, http.StatusOK, r.Code)
		})
}
```
